
services:
###> doctrine/doctrine-bundle ###
  database:
    ports:
      - "5432"
###< doctrine/doctrine-bundle ###

  adminer:
    ports:
      - "8081:8080"

  nginx:
    ports:
      - "8080:80"

  minio:
    ports:
      - "9000:9000" # API S3
      - "9001:9001" # console web
